package com.fictadvisor.pryomka.domain.models

/** Data which user sends when authorizes using Telegram.
 * @param authDate date of authorization
 * @param firstName user's first name in the Telegram
 * @param id Telegram id
 * @param lastName user's last name in the Telegram (optional)
 * @param photoUrl user's photo url in the Telegram (optional)
 * @param userName user's tag in the Telegram (optional)
 * @param hash hash of all content sent that is calculated by Telegram rules */
data class TelegramData(
    val authDate: Long,
    val firstName: String,
    val id: Long,
    val lastName: String? = null,
    val photoUrl: String? = null,
    val userName: String? = null,
    val hash: String
) {
    /** Data check string generated by Telegram rules. */
    val dataCheckString get() = buildString {
        append("auth_date=$authDate\n")
        append("first_name=$firstName\n")
        append("id=$id")
        lastName?.let { append("last_name=$lastName") }
        photoUrl?.let { append("photo_url=$photoUrl") }
        userName?.let { append("username=$userName") }
    }
}
